name: con
on:
  push

concurrency: ci-${{ github.ref }}

jobs:
#  consecutiveness:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: mktcode/consecutive-workflow-action@e2e008186aa210faacd68ec30f6ac236f7e2f435
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}

  sleep:
    #runs-on: ubuntu-latest
    runs-on: ["${{github.run_id}}", self-hosted, t3a.medium]
    #needs: [ consecutiveness ]
    steps:
      - run: sleep 60
